local richtext = require("richtext.richtext")

function init(self)
	msg.post("@render:", "clear_color", { color = vmath.vector4(1, 0.4, 0, 0) } )
	local settings = {
		fonts = {
			system = {
				regular = hash("system_2"),
			},
		},
		width = 600,
		parent = gui.get_node("text_parent"),
		color = vmath.vector4(0.95, 0.95, 1.0, 1.0),
	}

	--local text = [[<size=1>Lara</size><br/><size=0.7>Well, hello there!</size><br/><size=0.7>What do we have here?</size><img=icons:waiting/>]]
	local text = [[<size=1>???</size><br/><size=0.7>Well, hello there!</size><br/><size=0.7>What do we have here?</size><img=icons:waiting/>]]		


	
	pprint(richtext.create(text, "system", settings))

end

function final(self)
	-- Add finalization code here
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add input-handling code here
	-- Remove this function if not needed
end
